### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Thibaut95** [PedroEmanuelCosta2/BallJump#1]
# Primaire
- [ ] Menu - (Thibaut)
- [ ] Sauvegarde des scores (dans un fichier) - (Pedro)
- [x] Game Over - (Pedro)
- [ ] Menu Game Over - (Pedro)
- [ ] Partage des scores par bluetooth - choix : tout les scores, dernier score ou meilleur score

# Secondaire
- [ ] Bouton pause
- [ ] Ajout de plateforme
- [ ] Ajout de mob
- [ ] Ajout de tir
- [ ] Préférence
